all:
  children:
    row1:
      hosts:
        foundation1.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.11
        foundation2.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.12
        foundation3.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.13
        foundation4.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.14
        foundation5.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.15
    row2:
      hosts:
        foundation10.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.20
        foundation6.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.16
        foundation7.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.17
        foundation8.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.18
        foundation9.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.19
    row3:
      hosts:
        foundation11.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.21
        foundation12.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.22
        foundation13.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.23
        foundation14.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.24
        foundation15.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.25
    row4:
      hosts:
        foundation16.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.26
        foundation17.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.27
        foundation18.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.28
    row5:
      hosts:
        foundation19.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.29
        foundation20.ilt.example.com:
          external_gw: 172.16.70.1
          external_ip: 172.16.70.30
    ungrouped: {}
