---
- name: Prepare foundation0 for deploying Remote Desktop
  hosts: localhost
  gather_facts: no
  tasks:
    - name: clear known_hosts
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /root/.ssh/known_hosts
        - /home/kiosk/.ssh/known_hosts

    - name: synchronize xrdp packages to content
      synchronize:
        src: epel_pkgs
        dest: /content/epel

    - name: create a local epel repo
      yum_repository:
        name: epel
        description: EPEL YUM repo for XRDP
        file: external_repos
        baseurl: file:///content/epel/epel_pkgs/
        gpgcheck: no


- name: Deploy XRPD and Network
  hosts: foundation15.ilt.example.com
  gather_facts: no
  serial:
    - 1
    - 4
    - 100%
  pre_tasks:
    - ping:

    - name: create a external repo
      yum_repository:
        name: epel
        description: EPEL YUM repo for XRDP
        file: external_repos
        baseurl: http://172.25.254.250/epel/epel_pkgs/
        gpgcheck: no
  roles:
    - config_net
    - kiosk_gdm
    - xrdp
  tasks:
    - name: reboot foundations
      reboot:
